/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface Hashtag
 */
export interface Hashtag {
    /**
     * 
     * @type {string}
     * @memberof Hashtag
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Hashtag
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Hashtag
     */
    mediaCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Hashtag
     */
    profilePicUrl?: string;
}

/**
 * Check if a given object implements the Hashtag interface.
 */
export function instanceOfHashtag(value: object): value is Hashtag {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HashtagFromJSON(json: any): Hashtag {
    return HashtagFromJSONTyped(json, false);
}

export function HashtagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hashtag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'mediaCount': json['media_count'] == null ? undefined : json['media_count'],
        'profilePicUrl': json['profile_pic_url'] == null ? undefined : json['profile_pic_url'],
    };
}

export function HashtagToJSON(json: any): Hashtag {
    return HashtagToJSONTyped(json, false);
}

export function HashtagToJSONTyped(value?: Hashtag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'media_count': value['mediaCount'],
        'profile_pic_url': value['profilePicUrl'],
    };
}

