/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface StoryStickerLink
 */
export interface StoryStickerLink {
    /**
     * 
     * @type {string}
     * @memberof StoryStickerLink
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof StoryStickerLink
     */
    linkTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryStickerLink
     */
    linkType?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryStickerLink
     */
    displayUrl?: string;
}

/**
 * Check if a given object implements the StoryStickerLink interface.
 */
export function instanceOfStoryStickerLink(value: object): value is StoryStickerLink {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function StoryStickerLinkFromJSON(json: any): StoryStickerLink {
    return StoryStickerLinkFromJSONTyped(json, false);
}

export function StoryStickerLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryStickerLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'linkTitle': json['link_title'] == null ? undefined : json['link_title'],
        'linkType': json['link_type'] == null ? undefined : json['link_type'],
        'displayUrl': json['display_url'] == null ? undefined : json['display_url'],
    };
}

export function StoryStickerLinkToJSON(json: any): StoryStickerLink {
    return StoryStickerLinkToJSONTyped(json, false);
}

export function StoryStickerLinkToJSONTyped(value?: StoryStickerLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'link_title': value['linkTitle'],
        'link_type': value['linkType'],
        'display_url': value['displayUrl'],
    };
}

