/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface StoryLocation
 */
export interface StoryLocation {
    /**
     * 
     * @type {Location}
     * @memberof StoryLocation
     */
    location: Location;
    /**
     * 
     * @type {number}
     * @memberof StoryLocation
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLocation
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLocation
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLocation
     */
    height?: number;
}

/**
 * Check if a given object implements the StoryLocation interface.
 */
export function instanceOfStoryLocation(value: object): value is StoryLocation {
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function StoryLocationFromJSON(json: any): StoryLocation {
    return StoryLocationFromJSONTyped(json, false);
}

export function StoryLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'location': LocationFromJSON(json['location']),
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function StoryLocationToJSON(json: any): StoryLocation {
    return StoryLocationToJSONTyped(json, false);
}

export function StoryLocationToJSONTyped(value?: StoryLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': LocationToJSON(value['location']),
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
    };
}

