/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface StoryMedia
 */
export interface StoryMedia {
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    z?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    rotation?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StoryMedia
     */
    isPinned?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoryMedia
     */
    isHidden?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoryMedia
     */
    isSticker?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoryMedia
     */
    isFbSticker?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    mediaPk: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMedia
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryMedia
     */
    productType?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryMedia
     */
    mediaCode?: string;
}

/**
 * Check if a given object implements the StoryMedia interface.
 */
export function instanceOfStoryMedia(value: object): value is StoryMedia {
    if (!('mediaPk' in value) || value['mediaPk'] === undefined) return false;
    return true;
}

export function StoryMediaFromJSON(json: any): StoryMedia {
    return StoryMediaFromJSONTyped(json, false);
}

export function StoryMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'z': json['z'] == null ? undefined : json['z'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'rotation': json['rotation'] == null ? undefined : json['rotation'],
        'isPinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'isHidden': json['is_hidden'] == null ? undefined : json['is_hidden'],
        'isSticker': json['is_sticker'] == null ? undefined : json['is_sticker'],
        'isFbSticker': json['is_fb_sticker'] == null ? undefined : json['is_fb_sticker'],
        'mediaPk': json['media_pk'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'productType': json['product_type'] == null ? undefined : json['product_type'],
        'mediaCode': json['media_code'] == null ? undefined : json['media_code'],
    };
}

export function StoryMediaToJSON(json: any): StoryMedia {
    return StoryMediaToJSONTyped(json, false);
}

export function StoryMediaToJSONTyped(value?: StoryMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'z': value['z'],
        'width': value['width'],
        'height': value['height'],
        'rotation': value['rotation'],
        'is_pinned': value['isPinned'],
        'is_hidden': value['isHidden'],
        'is_sticker': value['isSticker'],
        'is_fb_sticker': value['isFbSticker'],
        'media_pk': value['mediaPk'],
        'user_id': value['userId'],
        'product_type': value['productType'],
        'media_code': value['mediaCode'],
    };
}

