/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Location,
  Media,
  Story,
  StoryHashtag,
  StoryLink,
  StoryLocation,
  StoryMention,
  StorySticker,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LocationFromJSON,
    LocationToJSON,
    MediaFromJSON,
    MediaToJSON,
    StoryFromJSON,
    StoryToJSON,
    StoryHashtagFromJSON,
    StoryHashtagToJSON,
    StoryLinkFromJSON,
    StoryLinkToJSON,
    StoryLocationFromJSON,
    StoryLocationToJSON,
    StoryMentionFromJSON,
    StoryMentionToJSON,
    StoryStickerFromJSON,
    StoryStickerToJSON,
} from '../models/index';

export interface VideoDownloadByUrlVideoDownloadByUrlPostRequest {
    sessionid: string;
    url: string;
    filename?: string;
    folder?: string;
    returnFile?: boolean;
}

export interface VideoDownloadVideoDownloadPostRequest {
    sessionid: string;
    mediaPk: number;
    folder?: string;
    returnFile?: boolean;
}

export interface VideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
    sessionid: string;
    url: string;
    caption?: string;
    mentions?: Array<StoryMention>;
    locations?: Array<StoryLocation>;
    links?: Array<StoryLink>;
    hashtags?: Array<StoryHashtag>;
    stickers?: Array<StorySticker>;
}

export interface VideoUploadToStoryVideoUploadToStoryPostRequest {
    sessionid: string;
    file: Blob;
    caption?: string;
    mentions?: Array<StoryMention>;
    locations?: Array<StoryLocation>;
    links?: Array<StoryLink>;
    hashtags?: Array<StoryHashtag>;
    stickers?: Array<StorySticker>;
}

export interface VideoUploadVideoUploadByUrlPostRequest {
    sessionid: string;
    url: string;
    caption: string;
    thumbnail?: Blob;
    usertags?: Array<string>;
    location?: Location;
}

export interface VideoUploadVideoUploadPostRequest {
    sessionid: string;
    file: Blob;
    caption: string;
    thumbnail?: Blob;
    usertags?: Array<string>;
    location?: Location;
}

/**
 * 
 */
export class VideoApi extends runtime.BaseAPI {

    /**
     * Download video using URL     
     * Video Download By Url
     */
    async videoDownloadByUrlVideoDownloadByUrlPostRaw(requestParameters: VideoDownloadByUrlVideoDownloadByUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionid'] == null) {
            throw new runtime.RequiredError(
                'sessionid',
                'Required parameter "sessionid" was null or undefined when calling videoDownloadByUrlVideoDownloadByUrlPost().'
            );
        }

        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling videoDownloadByUrlVideoDownloadByUrlPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sessionid'] != null) {
            formParams.append('sessionid', requestParameters['sessionid'] as any);
        }

        if (requestParameters['url'] != null) {
            formParams.append('url', requestParameters['url'] as any);
        }

        if (requestParameters['filename'] != null) {
            formParams.append('filename', requestParameters['filename'] as any);
        }

        if (requestParameters['folder'] != null) {
            formParams.append('folder', requestParameters['folder'] as any);
        }

        if (requestParameters['returnFile'] != null) {
            formParams.append('returnFile', requestParameters['returnFile'] as any);
        }


        let urlPath = `/video/download/by_url`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download video using URL     
     * Video Download By Url
     */
    async videoDownloadByUrlVideoDownloadByUrlPost(requestParameters: VideoDownloadByUrlVideoDownloadByUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.videoDownloadByUrlVideoDownloadByUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download video using media pk     
     * Video Download
     */
    async videoDownloadVideoDownloadPostRaw(requestParameters: VideoDownloadVideoDownloadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionid'] == null) {
            throw new runtime.RequiredError(
                'sessionid',
                'Required parameter "sessionid" was null or undefined when calling videoDownloadVideoDownloadPost().'
            );
        }

        if (requestParameters['mediaPk'] == null) {
            throw new runtime.RequiredError(
                'mediaPk',
                'Required parameter "mediaPk" was null or undefined when calling videoDownloadVideoDownloadPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sessionid'] != null) {
            formParams.append('sessionid', requestParameters['sessionid'] as any);
        }

        if (requestParameters['mediaPk'] != null) {
            formParams.append('media_pk', requestParameters['mediaPk'] as any);
        }

        if (requestParameters['folder'] != null) {
            formParams.append('folder', requestParameters['folder'] as any);
        }

        if (requestParameters['returnFile'] != null) {
            formParams.append('returnFile', requestParameters['returnFile'] as any);
        }


        let urlPath = `/video/download`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download video using media pk     
     * Video Download
     */
    async videoDownloadVideoDownloadPost(requestParameters: VideoDownloadVideoDownloadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.videoDownloadVideoDownloadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload video to story by URL to file     
     * Video Upload To Story By Url
     */
    async videoUploadToStoryByUrlVideoUploadToStoryByUrlPostRaw(requestParameters: VideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Story>> {
        if (requestParameters['sessionid'] == null) {
            throw new runtime.RequiredError(
                'sessionid',
                'Required parameter "sessionid" was null or undefined when calling videoUploadToStoryByUrlVideoUploadToStoryByUrlPost().'
            );
        }

        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling videoUploadToStoryByUrlVideoUploadToStoryByUrlPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sessionid'] != null) {
            formParams.append('sessionid', requestParameters['sessionid'] as any);
        }

        if (requestParameters['url'] != null) {
            formParams.append('url', requestParameters['url'] as any);
        }

        if (requestParameters['caption'] != null) {
            formParams.append('caption', requestParameters['caption'] as any);
        }

        if (requestParameters['mentions'] != null) {
            formParams.append('mentions', requestParameters['mentions']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['locations'] != null) {
            formParams.append('locations', requestParameters['locations']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['links'] != null) {
            formParams.append('links', requestParameters['links']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['hashtags'] != null) {
            formParams.append('hashtags', requestParameters['hashtags']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['stickers'] != null) {
            formParams.append('stickers', requestParameters['stickers']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }


        let urlPath = `/video/upload_to_story/by_url`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryFromJSON(jsonValue));
    }

    /**
     * Upload video to story by URL to file     
     * Video Upload To Story By Url
     */
    async videoUploadToStoryByUrlVideoUploadToStoryByUrlPost(requestParameters: VideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Story> {
        const response = await this.videoUploadToStoryByUrlVideoUploadToStoryByUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload video to story     
     * Video Upload To Story
     */
    async videoUploadToStoryVideoUploadToStoryPostRaw(requestParameters: VideoUploadToStoryVideoUploadToStoryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Story>> {
        if (requestParameters['sessionid'] == null) {
            throw new runtime.RequiredError(
                'sessionid',
                'Required parameter "sessionid" was null or undefined when calling videoUploadToStoryVideoUploadToStoryPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling videoUploadToStoryVideoUploadToStoryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sessionid'] != null) {
            formParams.append('sessionid', requestParameters['sessionid'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['caption'] != null) {
            formParams.append('caption', requestParameters['caption'] as any);
        }

        if (requestParameters['mentions'] != null) {
            formParams.append('mentions', requestParameters['mentions']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['locations'] != null) {
            formParams.append('locations', requestParameters['locations']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['links'] != null) {
            formParams.append('links', requestParameters['links']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['hashtags'] != null) {
            formParams.append('hashtags', requestParameters['hashtags']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['stickers'] != null) {
            formParams.append('stickers', requestParameters['stickers']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }


        let urlPath = `/video/upload_to_story`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryFromJSON(jsonValue));
    }

    /**
     * Upload video to story     
     * Video Upload To Story
     */
    async videoUploadToStoryVideoUploadToStoryPost(requestParameters: VideoUploadToStoryVideoUploadToStoryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Story> {
        const response = await this.videoUploadToStoryVideoUploadToStoryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload photo by URL and configure to feed     
     * Video Upload
     */
    async videoUploadVideoUploadByUrlPostRaw(requestParameters: VideoUploadVideoUploadByUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Media>> {
        if (requestParameters['sessionid'] == null) {
            throw new runtime.RequiredError(
                'sessionid',
                'Required parameter "sessionid" was null or undefined when calling videoUploadVideoUploadByUrlPost().'
            );
        }

        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling videoUploadVideoUploadByUrlPost().'
            );
        }

        if (requestParameters['caption'] == null) {
            throw new runtime.RequiredError(
                'caption',
                'Required parameter "caption" was null or undefined when calling videoUploadVideoUploadByUrlPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sessionid'] != null) {
            formParams.append('sessionid', requestParameters['sessionid'] as any);
        }

        if (requestParameters['url'] != null) {
            formParams.append('url', requestParameters['url'] as any);
        }

        if (requestParameters['caption'] != null) {
            formParams.append('caption', requestParameters['caption'] as any);
        }

        if (requestParameters['thumbnail'] != null) {
            formParams.append('thumbnail', requestParameters['thumbnail'] as any);
        }

        if (requestParameters['usertags'] != null) {
            formParams.append('usertags', requestParameters['usertags']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', new Blob([JSON.stringify(MediaToJSON(requestParameters['location']))], { type: "application/json", }));
                    }


        let urlPath = `/video/upload/by_url`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaFromJSON(jsonValue));
    }

    /**
     * Upload photo by URL and configure to feed     
     * Video Upload
     */
    async videoUploadVideoUploadByUrlPost(requestParameters: VideoUploadVideoUploadByUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Media> {
        const response = await this.videoUploadVideoUploadByUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload photo and configure to feed     
     * Video Upload
     */
    async videoUploadVideoUploadPostRaw(requestParameters: VideoUploadVideoUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Media>> {
        if (requestParameters['sessionid'] == null) {
            throw new runtime.RequiredError(
                'sessionid',
                'Required parameter "sessionid" was null or undefined when calling videoUploadVideoUploadPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling videoUploadVideoUploadPost().'
            );
        }

        if (requestParameters['caption'] == null) {
            throw new runtime.RequiredError(
                'caption',
                'Required parameter "caption" was null or undefined when calling videoUploadVideoUploadPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sessionid'] != null) {
            formParams.append('sessionid', requestParameters['sessionid'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['caption'] != null) {
            formParams.append('caption', requestParameters['caption'] as any);
        }

        if (requestParameters['thumbnail'] != null) {
            formParams.append('thumbnail', requestParameters['thumbnail'] as any);
        }

        if (requestParameters['usertags'] != null) {
            formParams.append('usertags', requestParameters['usertags']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', new Blob([JSON.stringify(MediaToJSON(requestParameters['location']))], { type: "application/json", }));
                    }


        let urlPath = `/video/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaFromJSON(jsonValue));
    }

    /**
     * Upload photo and configure to feed     
     * Video Upload
     */
    async videoUploadVideoUploadPost(requestParameters: VideoUploadVideoUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Media> {
        const response = await this.videoUploadVideoUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
