/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    pk: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    videoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    thumbnailUrl: string;
    /**
     * 
     * @type {number}
     * @memberof Resource
     */
    mediaType: number;
}

/**
 * Check if a given object implements the Resource interface.
 */
export function instanceOfResource(value: object): value is Resource {
    if (!('pk' in value) || value['pk'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('mediaType' in value) || value['mediaType'] === undefined) return false;
    return true;
}

export function ResourceFromJSON(json: any): Resource {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resource {
    if (json == null) {
        return json;
    }
    return {
        
        'pk': json['pk'],
        'videoUrl': json['video_url'] == null ? undefined : json['video_url'],
        'thumbnailUrl': json['thumbnail_url'],
        'mediaType': json['media_type'],
    };
}

export function ResourceToJSON(json: any): Resource {
    return ResourceToJSONTyped(json, false);
}

export function ResourceToJSONTyped(value?: Resource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pk': value['pk'],
        'video_url': value['videoUrl'],
        'thumbnail_url': value['thumbnailUrl'],
        'media_type': value['mediaType'],
    };
}

