/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Hashtag } from './Hashtag';
import {
    HashtagFromJSON,
    HashtagFromJSONTyped,
    HashtagToJSON,
    HashtagToJSONTyped,
} from './Hashtag';

/**
 * 
 * @export
 * @interface StoryHashtag
 */
export interface StoryHashtag {
    /**
     * 
     * @type {Hashtag}
     * @memberof StoryHashtag
     */
    hashtag: Hashtag;
    /**
     * 
     * @type {number}
     * @memberof StoryHashtag
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryHashtag
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryHashtag
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryHashtag
     */
    height?: number;
}

/**
 * Check if a given object implements the StoryHashtag interface.
 */
export function instanceOfStoryHashtag(value: object): value is StoryHashtag {
    if (!('hashtag' in value) || value['hashtag'] === undefined) return false;
    return true;
}

export function StoryHashtagFromJSON(json: any): StoryHashtag {
    return StoryHashtagFromJSONTyped(json, false);
}

export function StoryHashtagFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryHashtag {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtag': HashtagFromJSON(json['hashtag']),
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function StoryHashtagToJSON(json: any): StoryHashtag {
    return StoryHashtagToJSONTyped(json, false);
}

export function StoryHashtagToJSONTyped(value?: StoryHashtag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtag': HashtagToJSON(value['hashtag']),
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
    };
}

