/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserShort } from './UserShort';
import {
    UserShortFromJSON,
    UserShortFromJSONTyped,
    UserShortToJSON,
    UserShortToJSONTyped,
} from './UserShort';

/**
 * 
 * @export
 * @interface StoryMention
 */
export interface StoryMention {
    /**
     * 
     * @type {UserShort}
     * @memberof StoryMention
     */
    user: UserShort;
    /**
     * 
     * @type {number}
     * @memberof StoryMention
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMention
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMention
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryMention
     */
    height?: number;
}

/**
 * Check if a given object implements the StoryMention interface.
 */
export function instanceOfStoryMention(value: object): value is StoryMention {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function StoryMentionFromJSON(json: any): StoryMention {
    return StoryMentionFromJSONTyped(json, false);
}

export function StoryMentionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryMention {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserShortFromJSON(json['user']),
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function StoryMentionToJSON(json: any): StoryMention {
    return StoryMentionToJSONTyped(json, false);
}

export function StoryMentionToJSONTyped(value?: StoryMention | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserShortToJSON(value['user']),
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
    };
}

