/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryLink
 */
export interface StoryLink {
    /**
     * 
     * @type {string}
     * @memberof StoryLink
     */
    webUri: string;
    /**
     * 
     * @type {number}
     * @memberof StoryLink
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLink
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLink
     */
    z?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLink
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLink
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryLink
     */
    rotation?: number;
}

/**
 * Check if a given object implements the StoryLink interface.
 */
export function instanceOfStoryLink(value: object): value is StoryLink {
    if (!('webUri' in value) || value['webUri'] === undefined) return false;
    return true;
}

export function StoryLinkFromJSON(json: any): StoryLink {
    return StoryLinkFromJSONTyped(json, false);
}

export function StoryLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryLink {
    if (json == null) {
        return json;
    }
    return {
        
        'webUri': json['webUri'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'z': json['z'] == null ? undefined : json['z'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'rotation': json['rotation'] == null ? undefined : json['rotation'],
    };
}

export function StoryLinkToJSON(json: any): StoryLink {
    return StoryLinkToJSONTyped(json, false);
}

export function StoryLinkToJSONTyped(value?: StoryLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webUri': value['webUri'],
        'x': value['x'],
        'y': value['y'],
        'z': value['z'],
        'width': value['width'],
        'height': value['height'],
        'rotation': value['rotation'],
    };
}

