/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryStickerLink } from './StoryStickerLink';
import {
    StoryStickerLinkFromJSON,
    StoryStickerLinkFromJSONTyped,
    StoryStickerLinkToJSON,
    StoryStickerLinkToJSONTyped,
} from './StoryStickerLink';

/**
 * 
 * @export
 * @interface StorySticker
 */
export interface StorySticker {
    /**
     * 
     * @type {string}
     * @memberof StorySticker
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StorySticker
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof StorySticker
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof StorySticker
     */
    y: number;
    /**
     * 
     * @type {number}
     * @memberof StorySticker
     */
    z?: number;
    /**
     * 
     * @type {number}
     * @memberof StorySticker
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof StorySticker
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof StorySticker
     */
    rotation?: number;
    /**
     * 
     * @type {StoryStickerLink}
     * @memberof StorySticker
     */
    storyLink?: StoryStickerLink;
    /**
     * 
     * @type {object}
     * @memberof StorySticker
     */
    extra?: object;
}

/**
 * Check if a given object implements the StorySticker interface.
 */
export function instanceOfStorySticker(value: object): value is StorySticker {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function StoryStickerFromJSON(json: any): StorySticker {
    return StoryStickerFromJSONTyped(json, false);
}

export function StoryStickerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorySticker {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'x': json['x'],
        'y': json['y'],
        'z': json['z'] == null ? undefined : json['z'],
        'width': json['width'],
        'height': json['height'],
        'rotation': json['rotation'] == null ? undefined : json['rotation'],
        'storyLink': json['story_link'] == null ? undefined : StoryStickerLinkFromJSON(json['story_link']),
        'extra': json['extra'] == null ? undefined : json['extra'],
    };
}

export function StoryStickerToJSON(json: any): StorySticker {
    return StoryStickerToJSONTyped(json, false);
}

export function StoryStickerToJSONTyped(value?: StorySticker | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'x': value['x'],
        'y': value['y'],
        'z': value['z'],
        'width': value['width'],
        'height': value['height'],
        'rotation': value['rotation'],
        'story_link': StoryStickerLinkToJSON(value['storyLink']),
        'extra': value['extra'],
    };
}

