/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserShort
 */
export interface UserShort {
    /**
     * 
     * @type {string}
     * @memberof UserShort
     */
    pk: string;
    /**
     * 
     * @type {string}
     * @memberof UserShort
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserShort
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserShort
     */
    profilePicUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UserShort
     */
    profilePicUrlHd?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserShort
     */
    isPrivate?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof UserShort
     */
    stories?: Array<any>;
}

/**
 * Check if a given object implements the UserShort interface.
 */
export function instanceOfUserShort(value: object): value is UserShort {
    if (!('pk' in value) || value['pk'] === undefined) return false;
    return true;
}

export function UserShortFromJSON(json: any): UserShort {
    return UserShortFromJSONTyped(json, false);
}

export function UserShortFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserShort {
    if (json == null) {
        return json;
    }
    return {
        
        'pk': json['pk'],
        'username': json['username'] == null ? undefined : json['username'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'profilePicUrl': json['profile_pic_url'] == null ? undefined : json['profile_pic_url'],
        'profilePicUrlHd': json['profile_pic_url_hd'] == null ? undefined : json['profile_pic_url_hd'],
        'isPrivate': json['is_private'] == null ? undefined : json['is_private'],
        'stories': json['stories'] == null ? undefined : json['stories'],
    };
}

export function UserShortToJSON(json: any): UserShort {
    return UserShortToJSONTyped(json, false);
}

export function UserShortToJSONTyped(value?: UserShort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pk': value['pk'],
        'username': value['username'],
        'full_name': value['fullName'],
        'profile_pic_url': value['profilePicUrl'],
        'profile_pic_url_hd': value['profilePicUrlHd'],
        'is_private': value['isPrivate'],
        'stories': value['stories'],
    };
}

