/* tslint:disable */
/* eslint-disable */
/**
 * instagrapi-rest
 * RESTful API Service for instagrapi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserShort } from './UserShort';
import {
    UserShortFromJSON,
    UserShortFromJSONTyped,
    UserShortToJSON,
    UserShortToJSONTyped,
} from './UserShort';

/**
 * 
 * @export
 * @interface Usertag
 */
export interface Usertag {
    /**
     * 
     * @type {UserShort}
     * @memberof Usertag
     */
    user: UserShort;
    /**
     * 
     * @type {number}
     * @memberof Usertag
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof Usertag
     */
    y: number;
}

/**
 * Check if a given object implements the Usertag interface.
 */
export function instanceOfUsertag(value: object): value is Usertag {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function UsertagFromJSON(json: any): Usertag {
    return UsertagFromJSONTyped(json, false);
}

export function UsertagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usertag {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserShortFromJSON(json['user']),
        'x': json['x'],
        'y': json['y'],
    };
}

export function UsertagToJSON(json: any): Usertag {
    return UsertagToJSONTyped(json, false);
}

export function UsertagToJSONTyped(value?: Usertag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserShortToJSON(value['user']),
        'x': value['x'],
        'y': value['y'],
    };
}

